# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Role of Gas in Galaxy Dynamics
email: info@gasingalaxiesconference.com
description: > # this means to ignore newlines until "baseurl:"
  A conference exploring the origins and evolutions of gas in galaxies.
baseurl: "http://gasingalaxiesconference.com" # the subpath of your site, e.g. /blog
url: "http://gasingalaxiesconference.com"
collections:
  - main
  - registration
  - motivation
  - location
  - program
# Build settings
markdown: kramdown

